# Generated by Django 6.1.1 on 2026-09-17 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherobservation',
            name='cloud_cover_mean',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='weatherobservation',
            name='humidity_mean',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='weatherobservation',
            name='pressure_mean',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='weatherobservation',
            name='rain_sum',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='weatherobservation',
            name='snowfall_sum',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='weatherobservation',
            name='temperature_mean',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='weatherobservation',
            name='weather_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='weatherobservation',
            name='wind_gusts_max',
            field=models.FloatField(null=True),
        ),
    ]
