# Generated by Django 6.1.1 on 2026-09-22 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_weatherobservation_cloud_cover_mean_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_origin', models.DateField()),
                ('forecast_date', models.DateField()),
                ('temperature_mean', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_forecasts', to='weather.location')),
            ],
            options={
                'ordering': ['forecast_date'],
                'constraints': [models.UniqueConstraint(fields=('location', 'forecast_origin', 'forecast_date'), name='unique_location_forecast_date')],
            },
        ),
    ]
